platform :ios, '11.0'
use_frameworks!

target 'Analytics_Tests' do
  pod 'PocketAnalytics/Core', :path => '../'
  pod 'PocketAnalytics/Facebook', :path => '../'
  pod 'PocketAnalytics/Firebase', :path => '../'
  pod 'PocketAnalytics/Tenjin', :path => '../'
  pod 'PocketAnalytics/AppsFlyer', :path => '../'
end
