platform :ios, '15.0'
use_frameworks!

target 'Analytics_Tests' do
  pod 'PocketAnalytics', :path => '../'
  pod 'PocketAnalyticsDrain/Facebook', :path => '../'
  pod 'PocketAnalyticsDrain/Firebase', :path => '../'
  pod 'PocketAnalyticsDrain/Tenjin', :path => '../'
  pod 'PocketAnalyticsDrain/AppMetrica', :path => '../'
end
