platform :ios, '11.0'
use_frameworks!

target 'Analytics_Tests' do
  pod 'Analytics/Core', :path => '../'
  pod 'Analytics/Facebook', :path => '../'
  pod 'Analytics/Tenjin', :path => '../'
  pod 'Analytics/Firebase', :path => '../'
end
