default_platform :ios
skip_docs
opt_out_usage

$scheme = 'Analytics-Example'
$workspace = './Example/Analytics.xcworkspace'
$specsrepo = 'git@github.com:pocket-ninja/specs.git'
$podspecs = [
  'PocketAnalytics.podspec', 
  'PocketAnalyticsDrain.podspec'
]

before_all do |lane, options|
  if options[:skip_checks]
    UI.message "Skipping git status checks"
  else
    ensure_git_status_clean
  end
end

lane :patch do
  update(type: "patch")
end

lane :minor do
  update(type: "minor")
end

lane :major do
  update(type: "major")
end

lane :submit_pod do |options|
  push_to_git_remote(
    local_branch: "main",
    remote_branch: "main",
    remote: "origin"
  )
  
  $podspecs.each do |spec|
    pod_push(
      path: spec,
      repo: $specsrepo,
      allow_warnings: true
    )
  end 
end

private_lane :update do |options|
  type = options[:type]

  if type == "none"
    UI.message("No version type found")
    return
  end
  
  version = nil
  $podspecs.each do |spec|
    version = version_bump_podspec(path: spec, bump_type: type)
  end
  
  UI.message("Version bumped: #{version}")

  git_commit(path: $podspecs, message: "Updating podspec")
  add_git_tag(tag: version)
end
